/*
Program: EECS 348 Assignment 2 - CEO Email Priority Queue

Description:
This program prioritizes emails for a busy CEO using a MaxHeap
implemented as a list-based (array-backed) priority queue, built
entirely from scratch (no pre-existing heap library/module).
Emails are ordered first by sender category (Boss, then Subordinate,
then Peer, then ImportantPerson, then OtherPerson), and within the
same category, by date (newest first). The program reads commands
from a test file given as a command-line argument and processes
EMAIL, NEXT, READ, and COUNT commands.

Inputs:
A test file path passed as argv[1]. The file contains one command
per line:
  EMAIL <sender category>,<subject line>,<date (MM-DD-YYYY)>
  NEXT
  READ
  COUNT

Output:
Terminal output for NEXT (Sender/Subject/Date) and COUNT
("There are N emails to read.").

Collaborators / Sources:
Baseline code generated by ChatGPT (OpenAI), accessed via the
ChatGPT web interface (chatgpt.com), using the shared prompt
documented in the GenAI Analysis PDF submitted with this assignment.
The baseline ChatGPT code has been modified by me to fix COUNT/NEXT
output text to match the exact format required by the assignment spec,
validate the sscanf() return value when parsing dates, and add a comment
on every single line, as required by the assignment.
No other collaborators were used.

Author: Bikramaditya Kowsik
Creation Date: 2026-09-17
Revision Date: 2026-09-17
Revisions: Modified ChatGPT-generated baseline for output-format
correctness, input validation, and full line-by-line commenting.
 */

#include <stdio.h>      // gives fopen, fgets, printf, sscanf, fprintf for reading files and printing text
#include <stdlib.h>     // gives malloc, realloc, free, exit for managing memory and stopping the program
#include <string.h>     // gives strcmp, strncmp, strncpy, strchr, strcspn for working with text (strings)

#define INITIAL_CAPACITY 10   // the heap's array starts with room for 10 emails before it needs to grow
#define MAX_SUBJECT 256       // the longest a subject line is allowed to be, in characters

// This struct groups together all the information about one email.
typedef struct {
    char category[20];         // text like "Boss" or "Peer", up to 19 characters plus a terminator
    char subject[MAX_SUBJECT]; // the subject line text of the email
    char date[11];              // the date as text, in MM-DD-YYYY format (10 characters plus a terminator)
    int categoryPriority;       // a number we calculate once so we don't have to compare text every time
    int dateValue;               // the date turned into one number (YYYYMMDD) so two dates are easy to compare
} Email;                          // we now have a new type called "Email" we can use like int or char

// This struct is the heap itself: a growable list of emails plus
// bookkeeping about how many emails are in it and how much room there is.
typedef struct {
    Email *items;   // a pointer to the start of an array of Email structs stored in memory
    int size;       // how many emails are currently stored in the array
    int capacity;   // how many emails the array currently has room for (whether used or not)
} MaxHeap;            // we now have a new type called "MaxHeap" we can use like int or char

/*
--- [ChatGPT-generated, unmodified] ---
This function looks at a category name and returns a number for it.
A bigger number means the email should be read sooner.
 */
int getCategoryPriority(const char *category) { // category is the text we were given, e.g. "Boss"
    if (strcmp(category, "Boss") == 0)         // strcmp returns 0 when the two texts are identical
        return 5;                             // Boss gets the highest priority number, 5
    if (strcmp(category, "Subordinate") == 0)// check if the text is exactly "Subordinate"
        return 4;                               // Subordinate is next highest, 4
    if (strcmp(category, "Peer") == 0)          // check if the text is exactly "Peer"
        return 3;                                 // Peer is next, 3
    if (strcmp(category, "ImportantPerson") == 0) // check if the text is exactly "ImportantPerson"
        return 2;                                 // ImportantPerson is next, 2
    if (strcmp(category, "OtherPerson") == 0)    // check if the text is exactly "OtherPerson"
        return 1;                                // OtherPerson is read last, priority 1

    return 0;// if nothing matched, give it the lowest priority, 0
}  // end of getCategoryPriority

/*
--- [Modified by author: added sscanf() return-value validation] ---
This function takes a date written as text (MM-DD-YYYY) and turns
it into a single whole number like 20250103, so two dates can be
compared with a simple greater-than check instead of comparing text.
 */
int getDateValue(const char *date) { // date is the text we were given, e.g. "01-03-2025"
    int month, day, year;            // three empty boxes we will fill in from the text

    // sscanf reads the text and tries to pull out three numbers separated by dashes.
    // It returns how many numbers it successfully found; we need all three.
    if (sscanf(date, "%d-%d-%d", &month, &day, &year) != 3) {  // if fewer than 3 numbers were found, the date is bad
        return 0;  // treat a bad/unreadable date as the oldest possible date
    }// end of the "bad date" check

    return year * 10000 + month * 100 + day;  // combine year, month, day into one number, e.g. 2025*10000+1*100+3
}  // end of getDateValue

/*
--- [ChatGPT-generated, unmodified] ---
This function decides whether email a should come before email b
in line (that is, whether a has higher priority than b).
 */
int higherPriority(Email a, Email b) { // a and b are the two emails we are comparing
    if (a.categoryPriority != b.categoryPriority)   // if their category priorities are different numbers
        return a.categoryPriority > b.categoryPriority; // whichever has the bigger number wins

    return a.dateValue > b.dateValue; // same category, so the newer date (bigger number) wins
} // end of higherPriority

/*
--- [ChatGPT-generated, unmodified] ---
This function swaps the contents of two Email variables in memory.
It is used while moving emails around inside the heap.
 */
void swapEmails(Email *a, Email *b) {   // a and b are pointers (memory addresses) of the two emails to swap
    Email temp = *a;       // copy everything from where a points into a temporary variable
    *a = *b;              // copy everything from where b points into where a points
    *b = temp;           // copy the original a (saved in temp) into where b points
} // end of swapEmails

/*
--- [ChatGPT-generated, unmodified] ---
This function sets up a brand-new, empty heap by allocating memory
for its array and resetting its counters.
 */
void initializeHeap(MaxHeap *heap) {       // heap is the MaxHeap we are setting up
    heap->items = malloc(INITIAL_CAPACITY * sizeof(Email));// ask the computer for room for 10 emails

    if (heap->items == NULL) {// malloc returns NULL if it could not get memory
        fprintf(stderr, "Memory allocation failed.\n");// print an error message to the error output
        exit(EXIT_FAILURE);// stop the whole program immediately
    }// end of the "out of memory" check

    heap->size = 0;// the heap starts with zero emails in it
    heap->capacity = INITIAL_CAPACITY;// record how many slots we currently have room for
}// end of initializeHeap

/*
--- [ChatGPT-generated, unmodified] ---
This function is called when the heap's array is full. It doubles
the array's size so more emails can be added.
 */
void resizeHeap(MaxHeap *heap) {   // heap is the MaxHeap that needs more room
    heap->capacity *= 2;      // double how much room we are asking for

    Email *newItems =          // ask the computer to resize the array in memory
        realloc(heap->items, heap->capacity * sizeof(Email));// realloc grows the block, keeping existing data

    if (newItems == NULL) { // realloc returns NULL if it could not get memory
        fprintf(stderr, "Memory allocation failed.\n"); // print an error message to the error output
        free(heap->items); // release the old memory since we are quitting
        exit(EXIT_FAILURE);// stop the whole program immediately
    }  // end of the "out of memory" check

    heap->items = newItems;// point the heap at the newly grown array
}// end of resizeHeap

/*
--- [ChatGPT-generated, unmodified] ---
This function adds one new email into the heap, then re-arranges
things so the heap stays correctly ordered by priority.
 */
void insertEmail(MaxHeap *heap, Email email) {// heap is where we're inserting, email is the new one to add
    if (heap->size == heap->capacity)// if the array is completely full
        resizeHeap(heap);// make more room before we try to add anything

    int index = heap->size;// the new email will go in the next free slot
    heap->items[index] = email;// copy the new email into that slot
    heap->size++; // we now have one more email in the heap

    // Bubble the new email upward while it outranks its parent.
    while (index > 0) { // keep going as long as we are not at the very top
        int parent = (index - 1) / 2;// formula for finding the parent slot in the array

        if (!higherPriority(heap->items[index],                    // if the new email does NOT outrank its parent
                            heap->items[parent]))
            break;                                                    // stop moving it, it is in the right spot now

        swapEmails(&heap->items[index],                                // otherwise, swap it with its parent
                   &heap->items[parent]);

        index = parent;// continue checking from the parent's old spot
    }// end of the bubble-up loop
} // end of insertEmail

/*
--- [ChatGPT-generated, unmodified] ---
This function removes the highest-priority email (the very front
of the line) from the heap.
 */
int removeMax(MaxHeap *heap, Email *result) {   // heap is where we remove from, result is where to save the removed email (or NULL)
    if (heap->size == 0)                       // if there are no emails at all
        return 0;   // signal failure, nothing to remove

    if (result != NULL)     // if the caller wants a copy of the removed email
        *result = heap->items[0]; // save the top (highest priority) email into result

    heap->size--;   // we now have one fewer email in the heap

    if (heap->size == 0)  // if that was the last email
        return 1;  // we're done, nothing left to rearrange

    heap->items[0] = heap->items[heap->size];// move the last email in the array up to the top spot

    // Bubble the new top email downward to restore correct ordering.
    int index = 0; // start checking from the top of the heap

    while (1) {    // loop forever until we break out below
        int left = 2 * index + 1;  // formula for the left child's array slot
        int right = 2 * index + 2;    // formula for the right child's array slot
        int largest = index;    // assume the current slot is the highest priority for now

        if (left < heap->size &&                                           // if a left child actually exists
            higherPriority(heap->items[left],                               // and it outranks our current "largest" guess
                           heap->items[largest])) {
            largest = left;                                                   // then the left child is the new highest priority
        }                                                                       // end of checking the left child

        if (right < heap->size &&                                                // if a right child actually exists
            higherPriority(heap->items[right],  // and it outranks our current "largest" guess
                           heap->items[largest])) {
            largest = right;   // then the right child is the new highest priority
        }   // end of checking the right child

        if (largest == index)  // if neither child beat the current slot
            break;      // the heap is correctly ordered, stop

        swapEmails(&heap->items[index],           // otherwise, swap the current slot
                   &heap->items[largest]);       // with whichever child was higher priority

        index = largest;      // continue checking from that child's old spot
    }  // end of the bubble-down loop

    return 1;// signal success, an email was removed
} // end of removeMax

/*
--- [ChatGPT-generated, unmodified] ---
This function looks at the highest-priority email without removing
it from the heap.
 */
Email *peekMax(MaxHeap *heap) {           // heap is the MaxHeap we want to look at
    if (heap->size == 0)                    // if there are no emails at all
        return NULL;                          // there is nothing to point to, so return "nothing"

    return &heap->items[0];        // otherwise, return the memory address of the top email
}  // end of peekMax

/*
--- [ChatGPT-generated, unmodified] ---
This function reads one "EMAIL category,subject,date" line of text
and turns it into an Email struct that gets added to the heap.
 */
void processEmail(MaxHeap *heap, char *line) {   // heap is where to add it, line is the raw text line
    char *data = line + 6;      // skip past the literal word "EMAIL " (6 characters)

    char *firstComma = strchr(data, ',');    // find the first comma, which ends the category field
    if (firstComma == NULL)   // if there is no comma at all
        return;      // the line is broken, so just ignore it

    *firstComma = '\0';   // replace that comma with a string-ending character

    char *subject = firstComma + 1;  // the subject text starts right after that comma
    char *secondComma = strchr(subject, ',');   // find the next comma, which ends the subject field

    if (secondComma == NULL)  // if there is no second comma
        return;           // the line is broken, so just ignore it

    *secondComma = '\0'; // replace that comma with a string-ending character

    char *date = secondComma + 1;  // the date text starts right after that comma

    Email email;   // create a new, empty Email to fill in

    strncpy(email.category, data, sizeof(email.category) - 1);// copy the category text into the struct safely
    email.category[sizeof(email.category) - 1] = '\0';// make sure it always ends properly

    strncpy(email.subject, subject, sizeof(email.subject) - 1);// copy the subject text into the struct safely
    email.subject[sizeof(email.subject) - 1] = '\0'; // make sure it always ends properly

    strncpy(email.date, date, sizeof(email.date) - 1); // copy the date text into the struct safely
    email.date[sizeof(email.date) - 1] = '\0'; // make sure it always ends properly

    email.categoryPriority = getCategoryPriority(email.category);// work out and store the priority number now
    email.dateValue = getDateValue(email.date);// work out and store the date number now

    insertEmail(heap, email);  // add this fully-built email into the heap
}// end of processEmail

/*
--- [Modified by author: fixed COUNT/NEXT output text to match the
exact wording required by the assignment specification] ---
This function reads every line of the test file and does whatever
that line asks (add an email, show the next one, mark one as read,
or show how many are left).
 */
void processFile(FILE *file) {           // file is the already-opened test file we are reading from
    MaxHeap heap;                          // create a MaxHeap variable to use for this run
    initializeHeap(&heap);                   // set it up as an empty heap before we start

    char line[512];  // a temporary buffer to hold one line of text at a time

    while (fgets(line, sizeof(line), file) != NULL) {   // read one line at a time until the file runs out
        // Strip trailing newline/carriage-return characters.
        line[strcspn(line, "\r\n")] = '\0';                // cut off the invisible newline at the end of the line

        if (strncmp(line, "EMAIL ", 6) == 0) {    // if the line starts with the word "EMAIL "
            processEmail(&heap, line);            // hand it off to processEmail to add it to the heap
        }                                        ]// end of the EMAIL case
        else if (strcmp(line, "NEXT") == 0) {     // if the line is exactly the word "NEXT"
            Email *email = peekMax(&heap);      // look at (but don't remove) the top email

            if (email == NULL) {    // if there was no top email (heap is empty)
                printf("There are no emails to read.\n"); // print a clear message saying so
            } // end of the empty case
            else {// otherwise there is an email to show
                printf("Next email:\n");// print the required header line
                printf("Sender: %s\n", email->category);// print the sender's category
                printf("Subject: %s\n", email->subject);// print the subject line
                printf("Date: %s\n", email->date);// print the date
            }  // end of the "email exists" case
        } // end of the NEXT case
        else if (strcmp(line, "READ") == 0) { // if the line is exactly "READ"
            // No output is produced for READ. Passing NULL means we don't
            // need a copy of the removed email, and this also correctly
            // handles two READs in a row (the second READ just removes
            // the next email quietly), and does nothing if already empty.
            removeMax(&heap, NULL); // remove the top email, if any
        }  // end of the READ case
        else if (strcmp(line, "COUNT") == 0) {// if the line is exactly "COUNT"
            printf("There are %d emails to read.\n", heap.size);// print how many emails remain
        }\ // end of the COUNT case
        // Any other/unrecognized line is silently ignored.
    }// end of the main reading loop

    free(heap.items);  // give back the heap's memory when done
}// end of processFile

/*
--- [ChatGPT-generated, unmodified] ---
This is where the program starts running. It opens the test file
named on the command line and processes it.
 */
int main(int argc, char *argv[]) {// argc is how many arguments were given, argv is the list of them
    FILE *file;// will hold the opened test file

    if (argc != 2) {     // we expect exactly one extra argument: the file name
        fprintf(stderr, "Usage: %s <test-file>\n", argv[0]);   // remind the user how to run the program correctly
        return EXIT_FAILURE;     // stop the program and report failure
    }                             // end of the "wrong number of arguments" check

    file = fopen(argv[1], "r");   // try to open the given file name for reading

    if (file == NULL) {  // fopen returns NULL if it could not open the file
        perror("Could not open test file");// print a helpful system error message
        return EXIT_FAILURE;// stop the program and report failure
    }// end of the "file didn't open" check

    processFile(file); // go through the file and run all its commands

    fclose(file);// close the file since we are done with it

    return EXIT_SUCCESS;// tell the operating system we finished successfully
}// end of main
